// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: getfeedfromurl.sql

package database

import (
	"context"
)

const getFeedFromURL = `-- name: GetFeedFromURL :one
SELECT id, created_at, updated_at, name, url, user_id FROM feeds
where url = $1
`

func (q *Queries) GetFeedFromURL(ctx context.Context, url string) (Feed, error) {
	row := q.db.QueryRowContext(ctx, getFeedFromURL, url)
	var i Feed
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.Url,
		&i.UserID,
	)
	return i, err
}
