// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: getnamefromuuid.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const getNameFromUUID = `-- name: GetNameFromUUID :one
SELECT name FROM users
where ID = $1
`

func (q *Queries) GetNameFromUUID(ctx context.Context, id uuid.UUID) (string, error) {
	row := q.db.QueryRowContext(ctx, getNameFromUUID, id)
	var name string
	err := row.Scan(&name)
	return name, err
}
